exports.keys = [  
    {  
       object:"apps.getInstalledApps",
       name:"getInstalledApps"
    },
    {  
       object:"control.KEY_POWER",
       name:"on/off"
    },
    {  
       object:"control.KEY_UP",
       name:"arrow up"
    },
    {  
       object:"control.KEY_DOWN",
       name:"arrow down"
    },
    {  
       object:"control.KEY_LEFT",
       name:"arrow left"
    },
    {  
       object:"control.KEY_RIGHT",
       name:"arrow right"
    },
    {  
       object:"control.KEY_CHUP",
       name:"channel up"
    },
    {  
       object:"control.KEY_CHDOWN",
       name:"chhannel down"
    },
    {  
       object:"control.KEY_CH_LIST",
       name:"channel list"
    },
    {  
       object:"control.KEY_ENTER",
       name:"enter"
    },
    {  
       object:"control.KEY_RETURN",
       name:"return"
    },
    {  
       object:"control.KEY_MENU",
       name:"menu"
    },
    {  
       object:"control.KEY_SOURCE",
       name:"source"
    },
    {  
       object:"control.KEY_GUIDE",
       name:"guide"
    },
    {  
       object:"control.KEY_TOOLS",
       name:"tools"
    },
    {  
       object:"control.KEY_INFO",
       name:"info"
    },
    {  
       object:"control.KEY_RED",
       name:"red"
    },
    {  
       object:"control.KEY_BLUE",
       name:"blue"
    },
    {  
       object:"control.KEY_GREEN",
       name:"green"
    },
    {  
       object:"control.KEY_YELLOW",
       name:"yellow"
    },
    {  
       object:"control.KEY_VOLUP",
       name:"volume up"
    },
    {  
       object:"control.KEY_VOLDOWN",
       name:"volume down"
    },
    {  
       object:"control.KEY_MUTE",
       name:"volume mute"
    },
    {  
       object:"control.KEY_0",
       name:"0"
    },
    {  
       object:"control.KEY_1",
       name:"1"
    },
    {  
       object:"control.KEY_2",
       name:"2"
    },
    {  
       object:"control.KEY_3",
       name:"3"
    },
    {  
       object:"control.KEY_4",
       name:"4"
    },
    {  
       object:"control.KEY_5",
       name:"5"
    },
    {  
       object:"control.KEY_6",
       name:"6"
    },
    {  
       object:"control.KEY_7",
       name:"7"
    },
    {  
       object:"control.KEY_8",
       name:"8"
    },
    {  
       object:"control.KEY_9",
       name:"9"
    },
    {  
       object:"control.KEY_DTV",
       name:"dtv"
    },
    {  
       object:"control.KEY_HDMI",
       name:"hdmi"
    },
    {  
       object:"control.KEY_CONTENTS",
       name:"contents"
    }
 ];