exports.keys = [ 
   {  
      object:"command.volup_x3",
      name:"KEY_VOLUP,KEY_VOLUP,KEY_VOLUP"
   },
   {  
      object:"command.voldown_x3",
      name:"KEY_VOLDOWN,KEY_VOLDOWN,KEY_VOLDOWN"
   },
   {  
      object:"command.ch_13",
      name:"KEY_1,KEY_3"
   }, 
   {  
       object:"apps.getInstalledApps",
       name:"getInstalledApps"
   },
   {  
      object:"config.getToken",
      name:"getToken"
   },
    {  
       object:"control.KEY_POWER",
       name:""
    },
    {  
       object:"control.KEY_UP",
       name:""
    },
    {  
       object:"control.KEY_DOWN",
       name:""
    },
    {  
       object:"control.KEY_LEFT",
       name:""
    },
    {  
       object:"control.KEY_RIGHT",
       name:""
    },
    {  
       object:"control.KEY_CHUP",
       name:""
    },
    {  
       object:"control.KEY_CHDOWN",
       name:""
    },
    {  
       object:"control.KEY_CH_LIST",
       name:""
    },
    {  
       object:"control.KEY_ENTER",
       name:""
    },
    {  
       object:"control.KEY_RETURN",
       name:""
    },
    {  
       object:"control.KEY_MENU",
       name:""
    },
    {  
      object:"control.KEY_HOME",
      name:""
    },
    {  
       object:"control.KEY_SOURCE",
       name:""
    },
    {  
       object:"control.KEY_GUIDE",
       name:""
    },
    {  
       object:"control.KEY_TOOLS",
       name:""
    },
    {  
       object:"control.KEY_INFO",
       name:""
    },
    {  
       object:"control.KEY_RED",
       name:""
    },
    {  
       object:"control.KEY_BLUE",
       name:""
    },
    {  
       object:"control.KEY_GREEN",
       name:""
    },
    {  
       object:"control.KEY_YELLOW",
       name:""
    },
    {  
       object:"control.KEY_VOLUP",
       name:""
    },
    {  
       object:"control.KEY_VOLDOWN",
       name:""
    },
    {  
       object:"control.KEY_MUTE",
       name:""
    },
    {  
       object:"control.KEY_0",
       name:""
    },
    {  
       object:"control.KEY_1",
       name:""
    },
    {  
       object:"control.KEY_2",
       name:""
    },
    {  
       object:"control.KEY_3",
       name:""
    },
    {  
       object:"control.KEY_4",
       name:""
    },
    {  
       object:"control.KEY_5",
       name:""
    },
    {  
       object:"control.KEY_6",
       name:""
    },
    {  
       object:"control.KEY_7",
       name:""
    },
    {  
       object:"control.KEY_8",
       name:""
    },
    {  
       object:"control.KEY_9",
       name:""
    },
    {  
       object:"control.KEY_DTV",
       name:""
    },
    {  
       object:"control.KEY_HDMI",
       name:""
    },
    {  
       object:"control.KEY_CONTENTS",
       name:""
    },
    {  
      object:"control.KEY_PRECH",
      name:""
   },
   {  
      object:"control.KEY_CYAN",
      name:""
   },
   {  
      object:"control.KEY_ADDDEL",
      name:""
   },
   {  
      object:"control.KEY_PIP_ONOFF",
      name:""
   },
   {  
      object:"control.KEY_PIP_SWAP",
      name:""
   },
   {  
      object:"control.KEY_PLUS100",
      name:""
   },
   {  
      object:"control.KEY_CAPTION",
      name:""
   },
   {  
      object:"control.KEY_PMODE",
      name:""
   },
   {  
      object:"control.KEY_TTX_MIX",
      name:""
   },
   {  
      object:"control.KEY_TV",
      name:""
   },
   {  
      object:"control.KEY_PICTURE_SIZE",
      name:""
   },
   {  
      object:"control.KEY_AD",
      name:""
   },
   {  
      object:"control.KEY_PIP_SIZE",
      name:""
   },
   {  
      object:"control.KEY_MAGIC_CHANNEL",
      name:""
   },
   {  
      object:"control.KEY_PIP_SCAN",
      name:""
   },
   {  
      object:"control.KEY_PIP_CHUP",
      name:""
   },
   {  
      object:"control.KEY_PIP_CHDOWN",
      name:""
   },
   {  
      object:"control.KEY_DEVICE_CONNECT",
      name:""
   },
   {  
      object:"control.KEY_HELP",
      name:""
   },
   {  
      object:"control.KEY_ANTENA",
      name:""
   },
   {  
      object:"control.KEY_CONVERGENCE",
      name:""
   },
   {  
      object:"control.KEY_AUTO_PROGRAM",
      name:""
   },
   {  
      object:"control.KEY_FACTORY",
      name:""
   },
   {  
      object:"control.KEY_3SPEED",
      name:""
   },
   {  
      object:"control.KEY_RSURF",
      name:""
   },
   {  
      object:"control.KEY_ASPECT",
      name:""
   },
   {  
      object:"control.KEY_TOPMENU",
      name:""
   },
   {  
      object:"control.KEY_GAME",
      name:""
   },
   {  
      object:"control.KEY_QUICK_REPLAY",
      name:""
   },
   {  
      object:"control.KEY_STILL_PICTURE",
      name:""
   },
   {  
      object:"control.KEY_FAVCH",
      name:""
   },
   {  
      object:"control.KEY_REWIND",
      name:""
   },
   {  
      object:"control.KEY_STOP",
      name:""
   },
   {  
      object:"control.KEY_PLAY",
      name:""
   },
   {  
      object:"control.KEY_FF",
      name:""
   },
   {  
      object:"control.KEY_REC",
      name:""
   },
   {  
      object:"control.KEY_PAUSE",
      name:""
   },
   {  
      object:"control.KEY_INSTANT_REPLAY",
      name:""
   },
   {  
      object:"control.KEY_LINK",
      name:""
   },
   {  
      object:"control.KEY_FF_",
      name:""
   },
   {  
      object:"control.KEY_REWIND_",
      name:""
   },
   {  
      object:"control.KEY_ANGLE",
      name:""
   },
   {  
      object:"control.KEY_RESERVED1",
      name:""
   },
   {  
      object:"control.KEY_ZOOM1",
      name:""
   },
   {  
      object:"control.KEY_PROGRAM",
      name:""
   },
   {  
      object:"control.KEY_BOOKMARK",
      name:""
   },
   {  
      object:"control.KEY_DISC_MENU",
      name:""
   },
   {  
      object:"control.KEY_PRINT",
      name:""
   },
   {  
      object:"control.KEY_SUB_TITLE",
      name:""
   },
   {  
      object:"control.KEY_VCHIP",
      name:""
   },
   {  
      object:"control.KEY_REPEAT",
      name:""
   },
   {  
      object:"control.KEY_DOOR",
      name:""
   },
   {  
      object:"control.KEY_OPEN",
      name:""
   },
   {  
      object:"control.KEY_WHEEL_LEFT",
      name:""
   },
   {  
      object:"control.KEY_WHEEL_UP",
      name:""
   },
   {  
      object:"control.KEY_WHEEL_DOWN",
      name:""
   },
   {  
      object:"control.KEY_SLEEP",
      name:""
   },
   {  
      object:"control.KEY_DMA",
      name:""
   },
   {  
      object:"control.KEY_TURBO",
      name:""
   },
   {  
      object:"control.KEY_FM_RADIO",
      name:""
   },
   {  
      object:"control.KEY_DVR_MENU",
      name:""
   },
   {  
      object:"control.KEY_MTS",
      name:""
   },
   {  
      object:"control.KEY_PCMODE",
      name:""
   },
   {  
      object:"control.KEY_TTX_SUBFACE",
      name:""
   },
   {  
      object:"control.KEY_DNIe",
      name:""
   },
   {  
      object:"control.KEY_SRS",
      name:""
   },
   {  
      object:"control.KEY_CONVERT_AUDIO_MAINSUB",
      name:""
   },
   {  
      object:"control.KEY_MDC",
      name:""
   },
   {  
      object:"control.KEY_SEFFECT",
      name:""
   },
   {  
      object:"control.KEY_DTV_SIGNAL",
      name:""
   },
   {  
      object:"control.KEY_LIVE",
      name:""
   },
   {  
      object:"control.KEY_PERPECT_FOCUS",
      name:""
   },
   {  
      object:"control.KEY_ESAVING",
      name:""
   },
   {  
      object:"control.KEY_WHEEL_RIGHT",
      name:""
   },
   {  
      object:"control.KEY_VCR_MODE",
      name:""
   },
   {  
      object:"control.KEY_CATV_MODE",
      name:""
   },
   {  
      object:"control.KEY_DSS_MODE",
      name:""
   },
   {  
      object:"control.KEY_TV_MODE",
      name:""
   },
   {  
      object:"control.KEY_DVD_MODE",
      name:""
   },
   {  
      object:"control.KEY_CALLER_ID",
      name:""
   },
   {  
      object:"control.KEY_SCALE",
      name:""
   },
   {  
      object:"control.KEY_ZOOM_MOVE",
      name:""
   },
   {  
      object:"control.KEY_STB_MODE",
      name:""
   },
   {  
      object:"control.KEY_CLOCK_DISPLAY",
      name:""
   },
   {  
      object:"control.KEY_AV1",
      name:""
   },
   {  
      object:"control.KEY_AV2",
      name:""
   },
   {  
      object:"control.KEY_AV3",
      name:""
   },
   {  
      object:"control.KEY_SETUP_CLOCK_TIMER",
      name:""
   },
   {  
      object:"control.KEY_SVIDEO1",
      name:""
   },
   {  
      object:"control.KEY_COMPONENT1",
      name:""
   },
   {  
      object:"control.KEY_COMPONENT2",
      name:""
   },
   {  
      object:"control.KEY_MAGIC_BRIGHT",
      name:""
   },
   {  
      object:"control.KEY_HDMI1",
      name:""
   },
   {  
      object:"control.KEY_HDMI2",
      name:""
   },
   {  
      object:"control.KEY_HDMI3",
      name:""
   },
   {  
      object:"control.KEY_HDMI4",
      name:""
   },
   {  
      object:"control.KEY_W_LINK",
      name:""
   },
   {  
      object:"control.KEY_DTV_LINK",
      name:""
   },
   {  
      object:"control.KEY_APP_LIST",
      name:""
   },
   {  
      object:"control.KEY_BACK_MHP",
      name:""
   },
   {  
      object:"control.KEY_ALT_MHP",
      name:""
   },
   {  
      object:"control.KEY_ID_INPUT",
      name:""
   },
   {  
      object:"control.KEY_ID_SETUP",
      name:""
   },
   {  
      object:"control.KEY_ENTERTAINMENT",
      name:""
   },
   {  
      object:"control.KEY_RSS",
      name:""
   },
   {  
      object:"control.KEY_DNSe",
      name:""
   },
   {  
      object:"control.KEY_ANYNET",
      name:""
   },
   {  
      object:"control.KEY_POWEROFF",
      name:""
   },
   {  
      object:"control.KEY_POWERON",
      name:""
   },
   {  
      object:"control.KEY_ANYVIEW",
      name:""
   },
   {  
      object:"control.KEY_MS",
      name:""
   },
   {  
      object:"control.KEY_MORE",
      name:""
   },
   {  
      object:"control.KEY_PANNEL_POWER",
      name:""
   },
   {  
      object:"control.KEY_PANNEL_CHUP",
      name:""
   },
   {  
      object:"control.KEY_PANNEL_CHDOWN",
      name:""
   },
   {  
      object:"control.KEY_PANNEL_VOLUP",
      name:""
   },
   {  
      object:"control.KEY_PANNEL_VOLDOWN",
      name:""
   },
   {  
      object:"control.KEY_PANNEL_ENTER",
      name:""
   },
   {  
      object:"control.KEY_PANNEL_MENU",
      name:""
   },
   {  
      object:"control.KEY_PANNEL_SOURCE",
      name:""
   },
   {  
      object:"control.KEY_SVIDEO2",
      name:""
   },
   {  
      object:"control.KEY_SVIDEO3",
      name:""
   },
   {  
      object:"control.KEY_ZOOM2",
      name:""
   },
   {  
      object:"control.KEY_PANORAMA",
      name:""
   },
   {  
      object:"control.KEY_4_3",
      name:""
   },
   {  
      object:"control.KEY_16_9",
      name:""
   },
   {  
      object:"control.KEY_DYNAMIC",
      name:""
   },
   {  
      object:"control.KEY_STANDARD",
      name:""
   },
   {  
      object:"control.KEY_MOVIE1",
      name:""
   },
   {  
      object:"control.KEY_CUSTOM",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_RESET",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_LNA_ON",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_LNA_OFF",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_ANYNET_MODE_OK",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_ANYNET_AUTO_START",
      name:""
   },
   {  
      object:"control.KEY_AUTO_FORMAT",
      name:""
   },
   {  
      object:"control.KEY_DNET",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_CAPTION_ON",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_CAPTION_OFF",
      name:""
   },   
   {  
      object:"control.KEY_AUTO_ARC_PIP_DOUBLE",
      name:""
   },   
   {  
      object:"control.KEY_AUTO_ARC_PIP_LARGE",
      name:""
   },   
   {  
      object:"control.KEY_AUTO_ARC_PIP_SMALL",
      name:""
   },   
   {  
      object:"control.KEY_AUTO_ARC_PIP_WIDE",
      name:""
   },   
   {  
      object:"control.KEY_AUTO_ARC_PIP_LEFT_TOP",
      name:""
   },   
   {  
      object:"control.KEY_AUTO_ARC_PIP_RIGHT_TOP",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_PIP_LEFT_BOTTOM",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_PIP_RIGHT_BOTTOM",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_PIP_CH_CHANGE",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_AUTOCOLOR_SUCCESS",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_AUTOCOLOR_FAIL",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_C_FORCE_AGING",
      name:""
   },   
   {  
      object:"control.KEY_AUTO_ARC_USBJACK_INSPECT",
      name:""
   },
   {  
      object:"control.KEY_AUTO_ARC_JACK_IDENT",
      name:""
   },
   {  
      object:"control.KEY_NINE_SEPERATE",
      name:""
   },
   {  
      object:"control.KEY_ZOOM_IN",
      name:""
   },
   {  
      object:"control.KEY_ZOOM_OUT",
      name:""
   },
   {  
      object:"control.KEY_EXT1",
      name:""
   },
   {  
      object:"control.KEY_EXT2",
      name:""
   },
   {  
      object:"control.KEY_EXT3",
      name:""
   },
   {  
      object:"control.KEY_EXT4",
      name:""
   },
   {  
      object:"control.KEY_EXT5",
      name:""
   }
 ];
